mp.jwt.verify.issuer=expense-auth-service
smallrye.jwt.sign.key.location=keys/privateKey.pem
mp.jwt.verify.publickey.location=keys/publicKey.pem


quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

rabbitmq-host=${RABBITMQ_HOST}
rabbitmq-port=${RABBITMQ_PORT}
rabbitmq-username=${RABBITMQ_USERNAME}
rabbitmq-password=${RABBITMQ_PASSWORD}


mp.messaging.outgoing.user-registered-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.user-registered-out.exchange.name=user.events
mp.messaging.outgoing.user-registered-out.exchange.type=topic
mp.messaging.outgoing.user-registered-out.routing-keys=user.registered
mp.messaging.outgoing.user-registered-out.value.serializer=io.quarkus.jackson.ObjectMapperSerializer







