quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db

# optional but nice
quarkus.datasource.jdbc.max-size=8

# Authentication key
mp.jwt.verify.issuer=expense-auth-service
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

