apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-password-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-password-service
  template:
    metadata:
      labels:
        app: auth-password-service
    spec:
      containers:
        - name: auth-password-service
          image: image-registry.openshift-image-registry.svc:5000/group-7-felix/auth-password-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: auth-password-service-config

          env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql

            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: jdbc-uri

            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: username

            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: password
