apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-password-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/inholland-cloud-minor-2526/group-7-auth-service.git
    targetRevision: main
    path: k8s-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: group-7-felix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
