name: Build, Push & Deploy auth-service

on:
  push:
    branches:
      - user-registration

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/inholland-cloud-minor-2526/group-7-auth-service/auth-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build auth-service
        working-directory: auth-service
        run: ./mvnw clean package -DskipTests

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        working-directory: auth-service
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Install OpenShift CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/oc
          oc version

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify=true

      - name: Apply Kubernetes manifests
        run: |
          oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
          ooc apply -f k8s/postgres/
          oc apply -f k8s/rabbitmq/
          oc apply -f k8s/auth-service/

      - name: Deploy new auth-service image
        run: |
          oc set image deployment/auth-service \
            auth-service=$IMAGE_NAME:${{ github.sha }}
